export enum EnumTools {
    TEXT_SIZE = "text-size",
    TEXT_DIFF = "text-diff",
    TEXT_SORT = "text-sort",
    REGEX_TEST = "regex-test",
    URL_PARSE = "url-parse",
    URL_ENCODE = "url-encode",
    URL_DECODE = "url-decode",
    URL_COMPONENT_ENCODE = "url-component-encode",
    URL_COMPONENT_DECODE = "url-component-decode",
    CSP_PARSE = "csp-parse",
    CSP_UNPARSE = "csp-unparse",
    HTTP_CACHE_ANALYZE = "http-cache-analyze",
    HTTP_CORS_ANALYZE = "http-cors-analyze",
    BASE64_ENCODE = "base64-encode",
    BASE64_URL_SAFE_ENCODE = "base64-url-safe-encode",
    BASE64_DECODE = "base64-decode",
    SQL_FORMAT = "sql-format",
    SQL_COMPRESS = "sql-compress",
    SEMI_SPLIT = "semi-split",
    COMMA_SPLIT = "comma-split",
    LINE_SPLIT = "line-split",
    NGINX_LOG_PARSE = "nginx-log-parse",
    RANDOM_PASSWORD = "random-password",
    TEXT_SRT_PLAIN = "text-srt-plain",
}